### ISSUE TITLE
pip installation import error

### ISSUE THREAD

**Issue by pranjaldhole** [microprediction/pandemic#6]
When I pip installed `pandemic` and followed instructions according to README file and imported
```
from pandemic import run
```
I get the following import error 
```
cannot import name 'run' from 'pandemic.simulation'
```

**Comment by microprediction** [comment]
Can you supply the version of python you are using please?  


Can you import pandemic? 



Sent with BlackBerry Work
(www.blackberry.com)

**Comment by pranjaldhole** [comment]
My python version is `Python 3.7.4`.
No, `import pandamic` also throws the same error.

**Comment by microprediction** [comment]
Thanks Pranjal. Taking a look. What OS are you on?

**Comment by pranjaldhole** [comment]
I am using Ubuntu 18.04.4 LTS

**Comment by microprediction** [comment]
I pushed a new version that may fix it. Can you try?  That said, I am having some issues with one of my machines. Note for mac users, updating xcode *might* help too.

**Comment by pranjaldhole** [comment]
Yes, it works now. Thanks

**Comment by microprediction** [comment]
Terrific. The code will send results back now. Thanks for helping 


Sent with BlackBerry Work
(www.blackberry.com)
